- name: Install python3
  package:
    name: python3
    state: present

- block:
    - name: Install libvirt-nss
      package:
        name: libvirt-nss
        state: present
  rescue:
    - name: Install libnss-libvirt (Debian package name)
      package:
        name: libnss-libvirt
        state: present

- name: Create role directory
  file:
    path: /var/cache/ansible-role/libvirt_nss
    state: directory

- name: Generate modified nsswitch.conf
  script: "nsswitch.py /etc/nsswitch.conf
                       /var/cache/ansible-role/libvirt_nss/nsswitch.conf"
  changed_when: False
  check_mode: no

- name: Install modified nsswitch.conf
  copy:
    remote_src: yes
    src: /var/cache/ansible-role/libvirt_nss/nsswitch.conf
    dest: /etc/nsswitch.conf
    mode: "644"
