- name: Install python3
  package:
    name: python3
    state: present

- block:
    - name: Install libvirt-nss
      package:
        name: libvirt-nss
        state: present
  rescue:
    - name: Install libnss-libvirt (Debian package name)
      package:
        name: libnss-libvirt
        state: present

- name: Add libvirt-nss to nsswitch.conf
  script: nsswitch.py
  register: libvirt_nss_script
  changed_when: libvirt_nss_script.stdout|trim != ""
